In [1]:
import numpy as np

array1 = np.array([[3,4,5],
                   [7,8,9]])

print(array1)
print("********************")
print(array1.ndim) #boyutu
print("********************")
print(array1.shape) #şekli

[[3 4 5]
 [7 8 9]]
********************
2
********************
(2, 3)


In [2]:
print(np.zeros((5,5)))
print("**************")

print(np.ones((5,5)))
print("**************")

arr1 = np.full((5,5),"Merhaba")
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
**************
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
**************
[['Merhaba' 'Merhaba' 'Merhaba' 'Merhaba' 'Merhaba']
 ['Merhaba' 'Merhaba' 'Merhaba' 'Merhaba' 'Merhaba']
 ['Merhaba' 'Merhaba' 'Merhaba' 'Merhaba' 'Merhaba']
 ['Merhaba' 'Merhaba' 'Merhaba' 'Merhaba' 'Merhaba']
 ['Merhaba' 'Merhaba' 'Merhaba' 'Merhaba' 'Merhaba']]


In [3]:
arr1.dtype #matrisin içindekinin type'ı

dtype('<U7')

In [4]:
print(np.arange(0,1,0.2)) # start,stop,step

[0.  0.2 0.4 0.6 0.8]


In [5]:
print(np.linspace(0,2,num=5,endpoint=True)) #num böldüğü parça sayısı, stop yazılır.

[0.  0.5 1.  1.5 2. ]


In [6]:
print(np.random.randint(1,100,size=(5,5))) #1-100 random 5*5 matrix

[[56 23 97 21 11]
 [62 84 71 26 47]
 [47 28 90 24 87]
 [36 75 72 57  4]
 [60 32 79 82 89]]


In [7]:
customArray = np.array([[[1,2,3],[4,5,6]],        #3 boyutlu
                       [[7,8,9],[10,11,12]]])
print(customArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
print(np.ones((2,3,4))) #derinlik,satır,sütun

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [9]:
print(customArray[1][0][1:3]) #2.boyut 1.satır 2,3.sütunun elemanını yazdırdık

print("***************")

print(customArray[0:2,1,0]) #1,2.boyut 2.satır 1.sütunun elemanları

[8 9]
***************
[ 4 10]


In [10]:
newArray = np.array([1,2,3,4])
newArray2 = newArray.astype("f") #type'ını float yaptık
print(newArray2.dtype)

carray = newArray.copy()
varray = newArray.view()
newArray[1] = 444
carray[0] = 999
varray[0] = 555

print(newArray)
print(carray)
print(varray)
print(varray.base)
print(carray.base)

float32
[555 444   3   4]
[999   2   3   4]
[555 444   3   4]
[555 444   3   4]
None


In [11]:
yeniarray = np.array([1,2,3,4,5,6,7,8])
yeniarray2 = np.array(yeniarray, ndmin=2) #boyutunu değiştiriyor
print(yeniarray.shape)
print(yeniarray2.shape)

(8,)
(1, 8)


In [12]:
#reshape: Değerler katsayısı olmalı
arr1 = np.array([1,2,3,4,5,6,7,8])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

print(arr1.shape)
print(arr2.shape)
arrOneToTwo = arr1.reshape(2,4)
print(arrOneToTwo)
print(arrOneToTwo.reshape)

arrTwoToOne = arrOneToTwo.reshape(8)
print(arrTwoToOne)

arrTwoToTree = arr2.reshape(2,2,2)
print(arrTwoToTree)

(8,)
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
<built-in method reshape of numpy.ndarray object at 0x103706e50>
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
arr1 = np.array([1,2,3,4,5,6,7,8])
for i,eleman in enumerate(arr1):
    print(f"{i+1} eleman= {eleman}")

1 eleman= 1
2 eleman= 2
3 eleman= 3
4 eleman= 4
5 eleman= 5
6 eleman= 6
7 eleman= 7
8 eleman= 8


In [14]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
for eleman in arr2:
    for eleman2 in eleman:
        print(eleman2)

1
2
3
4
5
6
7
8


In [15]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for eleman in arr3:
    for eleman2 in eleman:
        for eleman3 in eleman2:
            print(eleman3)

1
2
3
4
5
6
7
8
9
10
11
12


In [16]:
for i in np.nditer(arr3):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [17]:
for i, eleman in np.ndenumerate(arr3):
    print(f"{i}. eleman= {eleman}")

(0, 0, 0). eleman= 1
(0, 0, 1). eleman= 2
(0, 0, 2). eleman= 3
(0, 1, 0). eleman= 4
(0, 1, 1). eleman= 5
(0, 1, 2). eleman= 6
(1, 0, 0). eleman= 7
(1, 0, 1). eleman= 8
(1, 0, 2). eleman= 9
(1, 1, 0). eleman= 10
(1, 1, 1). eleman= 11
(1, 1, 2). eleman= 12


Join İşlemleri

In [18]:
arr1 = np.array([[1,2],
                 [3,4]])
arr2 = np.array([[5,6],
                 [7,8]])
print(np.concatenate((arr1,arr2),axis=0)) #4,2
print("***********")
print(np.concatenate((arr1,arr2),axis=1)) #2,4

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
***********
[[1 2 5 6]
 [3 4 7 8]]


In [19]:
print(np.hstack((arr1,arr2))) #horizontal
print("***********")
print(np.vstack((arr1,arr2))) #vertical


[[1 2 5 6]
 [3 4 7 8]]
***********
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
print(np.stack((arr1,arr2),axis=0)) #3 boyutlu yaptı

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
print(np.stack((arr1,arr2),axis=1)) #dikeyde 3 boyutlu yaptı

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


Split İşlemleri

In [22]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2],[3,4],[5,6],[7,8]])
print(np.array_split(arr1,3)[0]) #Split 3, take first
print("**********************")
print(np.array_split(arr2,2))

[1 2]
**********************
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


Search İşlemleri

In [23]:
arr1 = np.array([1,2,3,4,5,5,5,5,5,5,6,7,5,8,5])
print(np.where(arr1==5))
print(np.where(arr1==5)[0]) #liste olarak döndürsün,arrayden kurtulsun diye [0]
print(np.where(arr1%2==0)[0])

(array([ 4,  5,  6,  7,  8,  9, 12, 14]),)
[ 4  5  6  7  8  9 12 14]
[ 1  3 10 13]


Sorting İşlemleri

In [24]:
arr1 = np.array([6,4,3,6,8,9,11,1])
arr2 = np.array(["Ceyda","Ahmet","İrem","Ozan","Veli"])
arr3 = np.array([True,False,False,True])

print(np.sort(arr1, kind="quicksort")[::-1])
print(np.sort(arr2, kind="mergesort"))
print(np.sort(arr3, kind="heapsort"))

[11  9  8  6  6  4  3  1]
['Ahmet' 'Ceyda' 'Ozan' 'Veli' 'İrem']
[False False  True  True]
